#!/bin/sh
# Make the clipboard persistent using xclip.
#
# This works by outputting the clipboard to a new xclip instance, which now
# owns the selection.

while clipnotify; do
	# Find the possible mime types of the selection
	ctypes=`xclip -out -selection clipboard -t TARGETS | grep '^.\+/.\+$'`
	if [ -z "$ctypes" ] || (echo "$ctypes" | grep -q 'text/plain'); then
		# If there are no results, or if plain is an option, use plain. Types
		# like text/html won't paste into everything.
		xclip -out -selection clipboard | xclip -selection clipboard
	else
		ctype=`echo "$ctypes" | head -n 1`
		xclip -out -selection clipboard | xclip -t "$ctype" -selection clipboard
	fi
done
