#!/usr/bin/env python3

import os
import subprocess
import tempfile
import sys

EDITOR = os.environ.get('EDITOR', 'vim')

def run_editor(s):
    with tempfile.NamedTemporaryFile(suffix='.tmp') as f:
        f.write(s.encode())
        f.flush()
        if subprocess.call(EDITOR.split() + [f.name]):
            sys.exit(1)
        f.seek(0)
        return f.read().decode()

def get_new_names(targets):
    target_doc = '\n'.join(t.replace('\n', '\0') for t in targets)
    destination_doc = run_editor(target_doc).strip()
    return [d.replace('\0', '\n') for d in destination_doc.split('\n')]

def main(args):
    targets = sorted(args)
    destinations = targets
    contmsg = "Press enter to continue."
    while True:
        destinations = get_new_names(destinations)
        if not all(destinations):
            input(f"Cannot rename to empty filename.\n{contmsg}")
            continue
        if len(targets) != len(destinations):
            input(f"Different number of of new and old names.\n{contmsg}")
            continue
        if len(destinations) != len(set(destinations)):
            input(f"Filenames must all be unique.\n{contmsg}")
            continue
        break
    for old, new in zip(targets, destinations):
        os.rename(old, new)

if __name__ == '__main__':
    if len(sys.argv) > 1:
        main(sys.argv[1:])
    else:
        main(os.listdir())
