#!/usr/bin/env python3

import os
import subprocess
import tempfile
import sys

EDITOR = os.environ.get('EDITOR', 'vim')

def run_editor(s):
    with tempfile.NamedTemporaryFile(suffix='.tmp') as f:
        f.write(s.encode())
        f.flush()
        if subprocess.call(EDITOR.split() + [f.name]):
            sys.exit(1)
        f.seek(0)
        return f.read().decode()

def get_new_names(targets):
    target_doc = '\n'.join(t.replace('\n', '\0') for t in targets)
    destination_doc = run_editor(target_doc).strip()
    return [d.replace('\0', '\n') for d in destination_doc.split('\n')]

def main(args):
    targets = sorted(args)
    destinations = get_new_names(targets)
    for t, d in zip(targets, destinations):
        if not d:
            sys.exit(f"Cannot rename {t} to empty filename. Aborting.")
    if len(targets) != len(destinations):
        sys.exit("Different number of of new and old names. Aborting.")
    if len(destinations) != len(set(destinations)):
        sys.exit("Filenames must all be unique. Aborting.")
    for old, new in zip(targets, destinations):
        os.rename(old, new)

if __name__ == '__main__':
    if len(sys.argv) > 1:
        main(sys.argv[1:])
    else:
        main(os.listdir())
