#!/usr/bin/env python3

import os
import subprocess
import tempfile
import sys

EDITOR = os.environ.get('EDITOR', 'vim')

def input_new_names(old_names):
    with tempfile.NamedTemporaryFile(suffix='.tmp') as fname_file:
        for old_name in old_names:
            fname_file.write((old_name.replace('\n', '\0') + '\n').encode())
        fname_file.flush()
        if subprocess.call(EDITOR.split() + [fname_file.name]):
            sys.exit(1)
        fname_file.seek(0)
        new_contents = fname_file.read()
    new_contents_lines = new_contents.decode().strip().split('\n')
    return [line.replace('\0', '\n') for line in new_contents_lines]

def main(args):
    targets = sorted(args)
    destinations = input_new_names(targets)
    if len(targets) != len(destinations):
        sys.exit("Different number of of new and old names. Aborting")
    for old, new in zip(targets, destinations):
        os.rename(old, new)

if __name__ == '__main__':
    if len(sys.argv) > 1:
        main(sys.argv[1:])
    else:
        main(os.listdir())
