#!/usr/bin/env python3

USAGE = """
Usage: {} <filename> [options]
Open the file with feh, and allow cycling through the rest of the directory.
""".strip()

import os.path
import sys

from shpy.shpy import *

if len(sys.argv[1]) < 2:
    print(USAGE.format(sys.argv[0]))
    sys.exit()

fname = os.path.abspath(sys.argv[1])
dirname = os.path.dirname(fname)
run("feh", dirname, "--start-at", fname, *sys.argv[2:])
