#!/bin/sh
PROPNAME='libinput Accel Speed'

if [ -n "$1" ]; then
	xinput set-prop "$1" "$PROPNAME" "$2"
	exit 0;
fi

cat << EOF
usage: $0 <device> <accel>

Set the mouse sensitivity (not acceleration)
The accel value between -1 and 1, where
 -0.5 is halved sensitivity,
  0.0 is no change,
  0.5 is doubled sensitivity, etc.

Available devices:
EOF

IFS=''
xinput list --name-only | while read name; do
	al=`xinput list-props "pointer:$name" 2>/dev/null | grep "$PROPNAME ("`
	if [ -n "$al" ]; then
		echo "'$name' ($(echo "$al" | cut -f 3))"
	fi
done
