#!/bin/sh
if [ -z "$1" ]; then
	echo "Usage: $0 <device> <accel>"
	echo
	echo "Set the mouse sensitivity (not acceleration)"
	echo "The accel value between -1 and 1, where"
	echo " -0.5 is "halved sensitivity,
	echo "  0.0 is no change,"
	echo "  0.5 is doubled sensitivity, etc."
	echo
	echo "Available devices:"
	IFS=''
	xinput list --name-only | while read name; do
		if xinput list-props "pointer:$name" 2>/dev/null | grep -q "libinput Accel Speed"; then
			echo "'$name'"
		fi;
	done
	exit
fi
xinput set-prop "$1" "libinput Accel Speed" "$2"
