#!/usr/bin/env python3

import re
import subprocess
import sys

if len(sys.argv) < 2:
    print("Usage: {} <findregex> [pythonregex]...")
    sys.exit()

_, fregex, *refinements = sys.argv

find_call = ['find', '-L', '.', '-iregex', '.*{}.*'.format(fregex)]
files = subprocess.check_output(find_call).decode().split('\n')[:-1]

for refinement in refinements:
    files = (f for f in files if re.search(refinement, f, re.IGNORECASE))

subprocess.call(['xdg-open', next(iter(files))])
