#!/bin/sh
cd ~

if [ -e "$XDG_CACHE_HOME/openmenu_list" ]; then
	f=$(dmenu -i -p "xdg-open" "$@" < "$XDG_CACHE_HOME/openmenu_list")
	if [ -n "$f" ]; then
		exec xdg-open "$f"
	fi
fi

find . -type f \
	\
	-not -path '*/\.git/*' \
	-not -path '*/\.hg/*' \
	-not -path '*/\.svn/*' \
	\
	-not -name '*.aux' \
	-not -name '*.db' \
	-not -name '*.o' \
	\
	-not -path './.cache/*' \
	-not -path './.config/Signal/*' \
	-not -path './.config/base16-*' \
	-not -path './.config/discord/*' \
	-not -path './.local/share/*' \
	-not -path './.mozilla/*' \
	-not -path './.zoom/*' \
	-not -path './git/*' \
	-not -path './old/*' \
> "$XDG_CACHE_HOME/openmenu_list"
