#!/bin/sh
pastadir="$HOME/pasta"
fname=$(stest -fl "$pastadir" | sort -u | dmenu -i -l 10)
ftype=$(file -b --mime-type "$pastadir/$fname")
if [ "$ftype" != "text/plain" ]; then
	xclip -t "$ftype" -selection clipboard "$pastadir/$fname"
else
	xclip -selection clipboard "$pastadir/$fname"
fi
