#!/usr/bin/env python3
import re
import sys

from shpy.shpy import *

try:
    gvariant_data = run('playerctl', 'metadata')
except Exception:
    sys.exit()

# In the absence of a GVariant parser, do some rudimentary parsing.
# This certainly will fail for arbitrary valid input, and will accept some
# invalid input, but it is resilient enough in practice to not be worth
# improving until it causes a problem.

# Key value pairs from GVariant data
gvariant_re   = r"'(?P<key>[\w:]+)': <(?P<value>.*?)>"
# Strings with potentially mismatched quote marks
string_re     = r"('|\")(?P<value>.*)('|\")"
# First value in a list (must be a string)
first_list_re = r"\[('|\")(?P<value>.*?)('|\")(,|\]).*"


metadata = dict(re.findall(gvariant_re, gvariant_data))

if not metadata:
    sys.exit()

def get_value(key, regex):
    return re.match(regex, metadata[key]).group('value')

title = get_value('xesam:title', string_re)
artist = get_value('xesam:artist', first_list_re)
print(title, '-', artist, '| ')
