#!/bin/sh
if [[ $# -eq 2 ]] ; then
	ffmpeg -i "$1" -ss "$2" -acodec copy -vcodec copy "${1%.*}-${2/:/.}.${1##*.}"
elif [[ $# -eq 3 ]] ; then
	ffmpeg -t "$3" -i "$1" -ss "$2" -acodec copy -vcodec copy "${1%.*}-${2/:/.}-${3/:/.}.${1##*.}"
else
	echo "Usage: trimvid <input.ext> <start> [end]"
fi
