#!/bin/zsh
if [ -z "$1" ]; then
	echo "Usage: urxvtsudo <command>"
	echo
	echo "Alternative to gksu, kdesu etc."
	exit
fi
cmdstr="$(pwd)\$$(for arg in "$@"; do printf ' %q' "$arg"; done)"
prompt="[urxvtsudo] password for %p to run as %U on %h: "
command="echo '$cmdstr'; sudo -p '$prompt' -k \"\$@\""
urxvt -g 80x2 -name floating -e zsh -c "$command" sudo "$@"
