#!/bin/sh
if [ -z "$1" ]; then
	echo "Usage: urxvtsudo [command]"
	echo
	echo "Alternative to gksu, kdesu etc."
	exit
fi
IFS=$'\n'
args="$*"
urxvt -name floating -e zsh -c "echo \"$args\" | xargs -d '\n' verbosudo"
