#!/bin/sh

BROWSER="surfcls floating -z 1.1"
HISTFILE="$HOME/.wikipedia_history"
CACHEDIR="/tmp/wikipedia"

# See https://gist.github.com/dannguyen/03a10e850656577cfb57
WGETARGS="--span-hosts --convert-links --no-directories --page-requisites"

# Allow a full stop at the end so that prefixes of previous searches work
rawquery=`tac "$HISTFILE" | dmenu -p "Wikipedia" -i -l 10 | sed 's/\.$//'`
[ -z "$rawquery" ] && exit 1

query=`echo "$rawquery" | xargs`
page="Special:Search?search=$query"
url="https://en.wikipedia.org/wiki/$page"

# A search term beginning with whitespace will not be added to history or cache
case "$rawquery" in
	' '*)
		exec $BROWSER "$url"
		;;
	*)
		echo "$query" >> "$HISTFILE"
		if [ ! -f "$CACHEDIR/$page" ]; then
			wget $WGETARGS --directory-prefix="$CACHEDIR" "$url"
			rm "$CACHEDIR/robots.txt"
		fi
		escapedpage="Special:Search%3Fsearch=$query" # Hacky
		exec $BROWSER "file://$CACHEDIR/$escapedpage"
		;;
esac
