#!/bin/sh
# Yes, I know wikipedia is not the only wiki

BROWSER="surfcls floating"
HISTFILE="$HOME/.wiki_history"
CACHEDIR="/tmp/wiki"

# Allow a full stop at the end so that prefixes of previous searches work
searchterm=`tac "$HISTFILE" | dmenu -p "Wikipedia" -i -l 10 | sed 's/\.$//'`

if [ -z "$searchterm" ]; then
	exit 1
fi

# A search term beginning with whitespace will not be added to history
case "$searchterm" in
	' '*) ;;
	*)    echo "$searchterm" >> "$HISTFILE";;
esac
searchterm=`echo "$searchterm" | xargs`

page="Special:Search?search=$searchterm"
escapedpage="Special:Search%3Fsearch=$searchterm" # Hacky

if [ ! -f "$CACHEDIR/$page" ]; then
	# See https://gist.github.com/dannguyen/03a10e850656577cfb57
	wget --span-hosts --convert-links \
		--no-directories --page-requisites \
		--directory-prefix=/tmp/wiki \
		"https://en.wikipedia.org/wiki/$page"
fi
exec $BROWSER "file://$CACHEDIR/$escapedpage"
