#!/bin/sh
if [ -n "$1" ]; then
	theme=$1
elif [ -n "$BASE16_THEME" ]; then
	theme=$BASE16_THEME
else
	>&2 echo "Error: BASE16_THEME not set, and no theme supplied"
	exit 1
fi

{
cat ~/.config/base16-xresources/xresources/base16-$theme-256.Xresources
for i in $(seq 0 15); do
	printf "base16.%02X: base%02X\n" $i $i
done
cat ~/.Xresources
} | xrdb -merge
echo "Added base16-$theme to xrdb"
