#!/bin/bash

if [ -z "$1" ]; then
	echo "Usage: $0 <url>"
	echo
	echo "Stream the given video using mpv."
	echo "Combines the best video and audio streams, limiting to 1080p."
	exit
fi

yt="youtube-dl --no-playlist -o -"
ytvideo="$yt --write-sub --embed-subs -f bestvideo[height<=1080]"
ytaudio="$yt -f bestaudio"
mpvargs="--demuxer-max-bytes=1GiB"

# subs will be written to the working directory
mkdir -p /tmp/youtube
cd /tmp/youtube
$ytvideo -- "$1" | mpv $mpvargs - --audio-file=<($ytaudio -- "$1")
rm -f /tmp/youtube/-*.{srt,ass,vtt,lrc}
rmdir --ignore-fail-on-non-empty /tmp/youtube
