#!/usr/bin/env python3
from os import system
from sys import argv

# Example:
#     youtube-terminal.py foo bar
# calls youtube-dl 'ytsearch:foo bar' --max-downloads 1 -o - | mpv - --no-video

call_str = 'youtube-dl "ytsearch:{}" --max-downloads 1 -o -' \
           + ' | mpv - --no-video'
system(call_str.format(' '.join(argv[1:])))
