#!/usr/bin/env python3
from os import system
from sys import argv

# Example:
#     ytv foo bar
# calls youtube-dl 'ytsearch:foo bar' --max-downloads 1 -o - | mpv -'

call_str = 'youtube-dl "ytsearch:{}" --max-downloads 1 -o -' \
           + ' | mpv -'
system(call_str.format(' '.join(argv[1:])))
